server:
  port: 8081

spring:
  application:
    name: Meeting_Notes_Summariser
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: ${GROQ_BASE_URL}
      chat:
        model: ${GROQ_MODEL}

